<#
    build.ps1 - build PEMF (Pirates! Expanded Modding Framework).

    Usage:
        .\build.ps1               # build only
        .\build.ps1 -Deploy       # build, then install into the game folder
        .\build.ps1 -Package      # build, then produce a ready-to-extract zip
        .\build.ps1 -Deploy -Package

    Code signing (see docs/WINDOWS_SECURITY.md):
        .\build.ps1 -Sign -CertThumbprint <sha1>      # cert in the user store
        .\build.ps1 -Sign -PfxPath key.pfx -PfxPassword <pw>

    NOTE: there is no certificate.  The SignPath Foundation rejected us and paid
    signing is out of scope, so releases ship UNSIGNED.  The switches above are
    kept in case that ever changes.

    Unsigned means Smart App Control blocks the DLLs from loading with
    "Bad Image ... 0xC0E90002", and Defender may flag the download as
    Trojan:Win32/Wacatac.B!ml (a cloud ML false positive).  The version
    resources below are hygiene, not a cure.  Publish the SHA256 of what you
    ship - it is the only integrity check players have.
#>
[CmdletBinding()]
param(
    [switch]$Deploy,
    [switch]$Package,
    [switch]$Sign,
    [string]$CertThumbprint,
    [string]$PfxPath,
    [string]$PfxPassword,
    [string]$TimestampUrl = "http://timestamp.digicert.com",
    [string]$GameDir = "C:\GOG Games\Sid Meier's Pirates",
    # Bump this with each release. It is stamped into the DLL resources AND
    # logged on the first line of pemf.log, so a stale default is not cosmetic:
    # it makes a bug report name a version that was never shipped.
    [string]$Version = "0.2.3"
)

$ErrorActionPreference = 'Stop'
$root  = Split-Path -Parent $MyInvocation.MyCommand.Path
$build = Join-Path $root 'build'
New-Item -ItemType Directory -Force $build | Out-Null

# --- locate the x86 toolset -------------------------------------------------
$vswhere = "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe"
if (-not (Test-Path $vswhere)) { throw "vswhere.exe not found - is Visual Studio installed?" }
$vsPath = & $vswhere -latest -products * `
    -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 `
    -property installationPath
if (-not $vsPath) { throw "No VS install with the x86/x64 C++ toolset was found." }

$vcvars = Join-Path $vsPath 'VC\Auxiliary\Build\vcvarsall.bat'
if (-not (Test-Path $vcvars)) { throw "vcvarsall.bat not found at $vcvars" }
Write-Host "toolset : $vsPath" -ForegroundColor DarkGray

# --- one source of truth for the version -----------------------------------
# Generated here and #included by the .rc files, so -Version is the only place
# a version number is written.
$vp = $Version.Split('.')
while ($vp.Count -lt 4) { $vp += '0' }
$verN = ($vp[0..3] -join ',')
$verS = ($vp[0..3] -join '.')

$verHeader = @"
// Generated by build.ps1 -- do not edit.
#define PEMF_VER_N   $verN
#define PEMF_VER_S   "$verS"
#define PEMF_PRODUCT "Pirates! Expanded Modding Framework"
#define PEMF_COMPANY "PEMF Project"
#define PEMF_COPYRIGHT "Free to use and redistribute. Not affiliated with Firaxis, 2K or Atari."
"@
Set-Content -Path (Join-Path $build 'pemf_version.h') -Value $verHeader -Encoding ascii
Write-Host "version : $verS" -ForegroundColor DarkGray

# --- compile ----------------------------------------------------------------
# /LD dll, /O2, /MT static CRT (the game ships msvcr71 - do not depend on a
# runtime that may be absent), /GS- so the naked thunks get no stack-check
# prologue, /std:c++17 for inline variables.
$common = '/nologo /O2 /MT /GS- /W3 /EHsc /std:c++17 /DWIN32 /D_CRT_SECURE_NO_WARNINGS'

$cmd = @"
call "$vcvars" x86 >nul 2>&1
if errorlevel 1 exit /b 1
cd /d "$build"
echo === resources ===
rc /nologo /I "$build" /fo "$build\proxy.res" "$root\src\proxy\proxy.rc"
if errorlevel 1 exit /b 1
rc /nologo /I "$build" /fo "$build\core.res" "$root\src\core\core.rc"
if errorlevel 1 exit /b 1
echo === proxy ===
cl $common /LD "$root\src\proxy\proxy.cpp" /I"$build" /Fe:version.dll /link kernel32.lib user32.lib "$build\proxy.res" /DEF:"$root\src\proxy\proxy.def" /OUT:version.dll
if errorlevel 1 exit /b 1
echo === core ===
cl $common /LD "$root\src\core\core.cpp" /I"$root\src\core" /I"$build" /Fe:pemf_core.dll /link kernel32.lib user32.lib winmm.lib ole32.lib mfplat.lib mfreadwrite.lib mfuuid.lib "$build\core.res" /OUT:pemf_core.dll
if errorlevel 1 exit /b 1
exit /b 0
"@

$bat = Join-Path $build '_build.bat'
Set-Content -Path $bat -Value $cmd -Encoding ascii
& cmd.exe /c "`"$bat`""
if ($LASTEXITCODE -ne 0) { throw "build failed (exit $LASTEXITCODE)" }

$artifacts = @('version.dll', 'pemf_core.dll') | ForEach-Object { Join-Path $build $_ }

# --- sign -------------------------------------------------------------------
# Smart App Control ("VerifiedAndReputableDesktop") refuses to load unsigned
# DLLs: CodeIntegrity event 3077, status 0xC0E90002.  A signature is the only
# thing that clears it.  Note that SAC also weighs *reputation*, so a freshly
# signed build can still be blocked until it has been seen in the wild.
if ($Sign) {
    $signtool = Get-ChildItem "C:\Program Files (x86)\Windows Kits\10\bin" -Recurse -Filter signtool.exe -ErrorAction SilentlyContinue |
        Where-Object { $_.FullName -match '\\x64\\' } |
        Sort-Object FullName -Descending | Select-Object -First 1
    if (-not $signtool) { throw "signtool.exe not found - install the Windows SDK signing tools." }

    $args = @('sign', '/fd', 'SHA256', '/td', 'SHA256', '/tr', $TimestampUrl)
    if ($CertThumbprint)  { $args += @('/sha1', $CertThumbprint) }
    elseif ($PfxPath)     {
        if (-not (Test-Path $PfxPath)) { throw "pfx not found: $PfxPath" }
        $args += @('/f', $PfxPath)
        if ($PfxPassword) { $args += @('/p', $PfxPassword) }
    }
    else { throw "-Sign needs either -CertThumbprint or -PfxPath." }

    Write-Host "`n=== signing ===" -ForegroundColor Cyan
    & $signtool.FullName @args @artifacts
    if ($LASTEXITCODE -ne 0) { throw "signtool failed (exit $LASTEXITCODE)" }
}

Write-Host "`n=== artifacts ===" -ForegroundColor Green
foreach ($a in $artifacts) {
    $f = Get-Item $a
    # confirm we really produced 32-bit images
    $b  = [System.IO.File]::ReadAllBytes($f.FullName)
    $pe = [BitConverter]::ToInt32($b, 0x3C)
    $m  = [BitConverter]::ToUInt16($b, $pe + 4)
    $arch = if ($m -eq 0x14C) { 'x86-32' } elseif ($m -eq 0x8664) { 'x64 (WRONG)' } else { "0x$($m.ToString('X'))" }

    # a blank version block is what an anonymous, low-reputation binary looks
    # like to Windows - catch a resource that silently failed to link
    $vi = [System.Diagnostics.FileVersionInfo]::GetVersionInfo($f.FullName)
    $ver = if ($vi.FileVersion) { $vi.FileVersion } else { 'NO VERSION RESOURCE' }

    $sig = (Get-AuthenticodeSignature $f.FullName).Status
    "{0,-16} {1,8} bytes  {2}  v{3}  sig:{4}" -f $f.Name, $f.Length, $arch, $ver, $sig
}
if (-not $Sign) {
    Write-Host "  unsigned - will be blocked by Smart App Control (0xC0E90002)." -ForegroundColor DarkYellow
}

# --- the payload every install shares ---------------------------------------
function Copy-Payload([string]$dest) {
    New-Item -ItemType Directory -Force (Join-Path $dest 'PEMF\events') | Out-Null
    Copy-Item (Join-Path $build 'version.dll')   $dest -Force
    Copy-Item (Join-Path $build 'pemf_core.dll') $dest -Force
    Copy-Item (Join-Path $root 'content\PEMF\events\*.json') (Join-Path $dest 'PEMF\events') -Force
    # Tuning files are edited in place by players, so never overwrite one that
    # is already there -- a rebuild must not discard someone's balance pass.
    $kmSrc = Join-Path $root 'content\PEMF\KeyMap_WASD.ini'
    if (Test-Path $kmSrc) { Copy-Item $kmSrc (Join-Path $dest 'PEMF') -Force }
    # Audio ships as loose files -- overwrite these, they are ours not the
    # player's, unlike the tuning files below.
    $audioSrc = Join-Path $root ('content' + [char]92 + 'PEMF' + [char]92 + 'audio')
    if (Test-Path $audioSrc) {
        $audioDst = Join-Path $dest ('PEMF' + [char]92 + 'audio')
        New-Item -ItemType Directory -Force $audioDst | Out-Null
        Copy-Item (Join-Path $audioSrc '*') $audioDst -Force
    }
    foreach ($ini in @('suspicion.ini', 'storms.ini')) {
        $iniSrc = Join-Path $root "content\PEMF\$ini"
        $iniDst = Join-Path $dest "PEMF\$ini"
        if ((Test-Path $iniSrc) -and -not (Test-Path $iniDst)) {
            Copy-Item $iniSrc $iniDst -Force
        }
    }
    $docs = Join-Path $dest 'PEMF\docs'
    New-Item -ItemType Directory -Force $docs | Out-Null
    # WINDOWS_SECURITY.md ships too: a player whose download was quarantined or
    # whose game will not start needs it, and pointing them at a web page is no
    # help when the thing that failed was the download.
    foreach ($d in @('PLAYER_MANUAL.md', 'EVENT_AUTHORING.md', 'WINDOWS_SECURITY.md')) {
        $src = Join-Path $root "docs\$d"
        if (Test-Path $src) { Copy-Item $src $docs -Force }
    }
}

# --- deploy -----------------------------------------------------------------
if ($Deploy) {
    if (-not (Test-Path $GameDir)) { throw "game dir not found: $GameDir" }
    Write-Host "`n=== installing to $GameDir ===" -ForegroundColor Cyan
    Copy-Payload $GameDir
    Get-ChildItem $GameDir -Filter 'version.dll'   | ForEach-Object { "  -> $($_.Name)" }
    Get-ChildItem $GameDir -Filter 'pemf_core.dll' | ForEach-Object { "  -> $($_.Name)" }
    Get-ChildItem (Join-Path $GameDir 'PEMF\events') -Filter *.json |
        ForEach-Object { "  -> PEMF\events\$($_.Name)" }
    Write-Host "`nLog: $GameDir\pemf.log" -ForegroundColor Yellow
}

# --- package ----------------------------------------------------------------
if ($Package) {
    $dist  = Join-Path $root 'dist'
    $stage = Join-Path $dist "PEMF-$Version"
    if (Test-Path $stage) { Remove-Item $stage -Recurse -Force }
    New-Item -ItemType Directory -Force $stage | Out-Null

    Copy-Payload $stage
    Copy-Item (Join-Path $root 'INSTALL.txt') $stage -Force -ErrorAction SilentlyContinue

    $zip = Join-Path $dist "PEMF-$Version.zip"
    if (Test-Path $zip) { Remove-Item $zip -Force }
    Compress-Archive -Path (Join-Path $stage '*') -DestinationPath $zip -CompressionLevel Optimal

    Write-Host "`n=== package ===" -ForegroundColor Green
    Write-Host "  $zip  ($([math]::Round((Get-Item $zip).Length/1KB)) KB)"
    Write-Host "`n  contents:"
    Get-ChildItem $stage -Recurse -File |
        ForEach-Object { "    " + $_.FullName.Substring($stage.Length + 1) }

    # Publish-ready hashes.  docs\WINDOWS_SECURITY.md tells people to check the
    # download against these, so a release that ships without updating them
    # hands users numbers that match nothing -- which happened for three
    # releases running.  Print the table in the form the doc wants, and drop it
    # next to the zip so it cannot be forgotten between build and publish.
    $hashRows = @()
    $hashRows += [pscustomobject]@{ File = "PEMF-$Version.zip"; SHA256 = (Get-FileHash $zip -Algorithm SHA256).Hash }
    Get-ChildItem $stage -Recurse -File -Filter *.dll | Sort-Object Name | ForEach-Object {
        $hashRows += [pscustomobject]@{ File = $_.Name; SHA256 = (Get-FileHash $_.FullName -Algorithm SHA256).Hash }
    }

    $table  = "**Every release has its own hashes.** These are **$Version**:`r`n`r`n"
    $table += "| File | SHA256 |`r`n|---|---|`r`n"
    foreach ($r in $hashRows) { $table += "| ``$($r.File)`` | ``$($r.SHA256)`` |`r`n" }

    $hashFile = Join-Path $dist "PEMF-$Version.sha256.md"
    Set-Content -Path $hashFile -Value $table -Encoding utf8

    Write-Host "`n=== hashes ===" -ForegroundColor Green
    foreach ($r in $hashRows) { Write-Host ("    {0,-20} {1}" -f $r.File, $r.SHA256) }
    Write-Host "`n  markdown table written to $hashFile"
    Write-Host "  PASTE IT INTO docs\WINDOWS_SECURITY.md AND README.md BEFORE PUBLISHING." -ForegroundColor Yellow
}
