"""
gen_proxy.py - generate the full forwarding surface for the version.dll proxy.

Our DLL takes over the module name "version.dll" for the whole process, so it
must export everything the real one does -- not just what Pirates!.exe imports.
d3d9.dll, for one, pulls in GetFileVersionInfoW.

Reads the real system DLL's export table and emits:
    generated.inc   X-macro list of export names
    proxy.def       undecorated export names -> our stubs
"""
import os
import struct
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", "re", "scripts"))
from xref_scan import PE  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
REAL = os.path.join(os.environ.get("SystemRoot", r"C:\Windows"),
                    "System32", "version.dll")


def exports(path):
    pe = PE(path)
    rva, _ = struct.unpack_from("<II", pe.data, pe.datadir)
    o = pe.va_to_off(pe.imagebase + rva)
    (_c, _t, _v, _name, base, _nf, n_names,
     addr_rva, names_rva, ords_rva) = struct.unpack_from("<IIIIIIIIII", pe.data, o)

    def cstr(off):
        e = off
        while pe.data[e]:
            e += 1
        return pe.data[off:e].decode()

    no = pe.va_to_off(pe.imagebase + names_rva)
    out = []
    for i in range(n_names):
        nrva = struct.unpack_from("<I", pe.data, no + i * 4)[0]
        out.append(cstr(pe.va_to_off(pe.imagebase + nrva)))
    return sorted(out)


def main():
    names = exports(REAL)
    print(f"real version.dll exports: {len(names)}")

    with open(os.path.join(HERE, "generated.inc"), "w") as f:
        f.write("// Generated by gen_proxy.py -- do not edit.\n")
        f.write(f"// Source: {REAL}\n")
        for n in names:
            f.write(f"PROXY_EXPORT({n})\n")

    with open(os.path.join(HERE, "proxy.def"), "w") as f:
        f.write("; Generated by gen_proxy.py -- do not edit.\n")
        f.write("LIBRARY version\nEXPORTS\n")
        for n in names:
            f.write(f"    {n} = Proxy_{n}\n")

    for n in names:
        print(f"    {n}")


if __name__ == "__main__":
    main()
