//Decompile the event/crew/morale functions of interest to a C file.
//@category Pirates
import ghidra.app.script.GhidraScript;
import ghidra.app.decompiler.DecompInterface;
import ghidra.app.decompiler.DecompileResults;
import ghidra.program.model.address.Address;
import ghidra.program.model.listing.Function;
import ghidra.program.model.symbol.Reference;
import ghidra.program.model.symbol.ReferenceIterator;

import java.io.FileWriter;
import java.io.PrintWriter;

public class DecompileTargets extends GhidraScript {

    private static final String[] TARGETS = {
        "004f60d0", // formatter core
        "004f6090", // AddText mode0
        "004f60b0", // AddText mode1
        "00404810", // GetCrewMoodString / morale score
        "004879f0", // ShowMessageCard candidate
        "004125a0", // mutiny site
        "00443dc0", // crew status site
        "00410321", // divide plunder
        "00437a5b", // morale delta A
        "00437ca6", // morale delta B
        "004608e0", // starving
    };

    private boolean dumpCallers = true;

    @Override
    public void run() throws Exception {
        String[] args = getScriptArgs();
        dumpCallers = (args == null || args.length <= 1);
        String[] targets = (args != null && args.length > 1) ? null : TARGETS;
        String outPath;
        if (args != null && args.length > 1) {
            outPath = args[0];
            targets = new String[args.length - 1];
            System.arraycopy(args, 1, targets, 0, args.length - 1);
        } else {
            outPath = "C:\\Users\\Shadow\\Projects\\PiratesMod\\re\\out\\decomp.c";
        }
        runOn(outPath, targets);
    }

    private void runOn(String outPath, String[] TARGETS) throws Exception {
        DecompInterface di = new DecompInterface();
        di.openProgram(currentProgram);

        PrintWriter out = new PrintWriter(new FileWriter(outPath));
        out.println("/* Auto-generated by DecompileTargets.java */");

        for (String t : TARGETS) {
            Address a = toAddr(t);
            Function f = getFunctionContaining(a);
            out.println();
            out.println("/* ===================================================");
            out.println(" * asked: " + t);
            if (f == null) {
                out.println(" * NO FUNCTION FOUND");
                out.println(" * =================================================== */");
                continue;
            }
            out.println(" * func : " + f.getName() + " @ " + f.getEntryPoint());
            out.println(" * conv : " + f.getCallingConventionName());
            out.println(" * =================================================== */");

            DecompileResults r = di.decompileFunction(f, 180, monitor);
            if (r != null && r.decompileCompleted()) {
                out.println(r.getDecompiledFunction().getC());
            } else {
                out.println("// decompile FAILED: "
                        + (r == null ? "null result" : r.getErrorMessage()));
            }
        }

        // Also dump callers of the two AddText wrappers so we can see every
        // place the game composes an event message. Only on the default run.
        out.println();
        out.println("/* ============ CALLERS OF AddText wrappers ============ */");
        for (String w : dumpCallers ? new String[]{"004f6090", "004f60b0"}
                                    : new String[]{}) {
            Address wa = toAddr(w);
            out.println("/* --- callers of " + w + " --- */");
            ReferenceIterator it = currentProgram.getReferenceManager()
                    .getReferencesTo(wa);
            int n = 0;
            while (it.hasNext()) {
                Reference ref = it.next();
                Function cf = getFunctionContaining(ref.getFromAddress());
                out.println("//   " + ref.getFromAddress()
                        + "  in " + (cf == null ? "<none>" : cf.getName()
                        + " @ " + cf.getEntryPoint()));
                n++;
            }
            out.println("//   total: " + n);
        }

        out.close();
        println("DecompileTargets wrote " + outPath);
    }
}
